### ISSUE TITLE
[BUG] Leading 0 in package declaration

### ISSUE THREAD

**Issue by MiliDurasovic** [nkuhn-vmw/tanzu-ai-samples#1]
After running `./gradlew clean assemble`, as described in the documentation. The build failed with the following error:
```
2024-01-25T15:57:31.954+0100 [ERROR] [system.err] 0package org.cloudfoundry.samples.music.web;
2024-01-25T15:57:31.954+0100 [ERROR] [system.err] ^
2024-01-25T15:57:31.977+0100 [ERROR] [system.err] 1 error
```

Found the issue in:
https://github.com/nkuhn-vmw/tanzu-ai-samples/blob/main/spring-music-taylors-version/src/main/java/org/cloudfoundry/samples/music/web/AIController.java#L1

After removing the leading 0 from the package declaration, the build succeeded and I was able to push the app.

**Comment by nkuhn-vmw** [comment]
Thank you -- I have corrected the accidental 0 place on the AIController

**Comment by nkuhn-vmw** [comment]
Issue resolved - closing
